import Footer from "../components/Footer";
import Navbar from "../components/Navbar"

function AboutPage(){

return(

<>
<Navbar/>

<br />

<div className="card bg-base-200 w-200 shadow-sm mx-auto border-2 border-cyan-700">
<figure>
    <img
      src="https://i.ytimg.com/vi/c0ZK7_ptKp4/maxresdefault.jpg"
      alt="Img Not Loading" />
  </figure>
  <div className="card-body">
    <h2 className="card-title mx-auto text-4xl">GAMEPLAY</h2>
    <p className="text-2xl">In this game, the player is in charge of the sectors of industry, ecosystems, people, and science, and need to carefully manage emissions and avoid disasters in order to reach a sustainable future. The game is not turn-based:
 it runs on real time, but there are controls to pause or speed up. The objective of the game is to get a winning card, and this is done by upgrading the ones already "bought" using the tokens generated by the sectors.</p>
  </div>
</div>

<br />
<br />
<div className="flex w-full flex-col lg:flex-row">




  <div className="card bg-base-200 rounded-box grid min-h-32 grow place-items-center ml-50 w-96 shadow-sm border-2 border-cyan-700"><div className="card-body text-2xl">
    <p>The player is free to decide how to build each sector, with each card most often speeding up the token production speed of its sector.
 Some cards increase emissions, others reduce it, and others are neutral, and most cards are means of getting other more advanced cards. The size of the sectors can be upgraded to allow more cards to be placed on it.</p>
  </div></div>




  <div className="divider lg:divider-horizontal"></div>
  <div className="card bg-base-200 rounded-box grid min-h-32 grow place-items-center w-96 shadow-sm border-2 border-cyan-700">  <div className="card-body text-2xl">
    <p className="">Random disaster cards are generated and placed on the top row of the game board, and the player needs to mitigate the crisis before the card timer ends and the disaster happens.
 The disasters can have any effect, from increasing emissions, through loss of resources, up to losing the game entirely.</p>
  </div></div>




  <div className="divider lg:divider-horizontal"></div>
  <div className="card bg-base-200 rounded-box grid min-h-32 grow place-items-center mr-50 w-96 shadow-sm border-2 border-cyan-700">  <div className="card-body text-2xl">
    <p className="">Out of the total 120 cards, there are 6 winning cards in the game:</p>
    <p className="">1. "Industry 22nd Century"</p>
    <p className="">2. "A Global Oasis"</p>
    <p className="">3. "Eco Symbiosis"</p>
    <p className="">4. "Planet B Colonized"</p>
    <p className="">5. "No Tech Civilization"</p>
    <p className="">6. "Planetary Thermostat"</p>


  </div></div>




</div>

<br />
<Footer/>
</>

)
}



export default AboutPage;